CREATE TABLE perfil (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- O "sub" do Keycloak é a chave natural. Não existe coluna de senha aqui,
    -- e é de propósito: senha é problema do Keycloak.
    sub             VARCHAR(64)  NOT NULL UNIQUE,
    email           VARCHAR(200) NOT NULL,
    nome            VARCHAR(200) NOT NULL,
    cpf             VARCHAR(14),
    celular         VARCHAR(20),
    data_nascimento DATE,
    cep             VARCHAR(9),
    rua             VARCHAR(200),
    numero          VARCHAR(20),
    bairro          VARCHAR(100),
    cidade          VARCHAR(100),
    estado          VARCHAR(2),
    criado_em       TIMESTAMPTZ  NOT NULL,
    atualizado_em   TIMESTAMPTZ
);

-- E-mail sempre em minúsculo (o código normaliza na escrita), então este
-- índice único também serve de trava contra o cadastro duplicado que a
-- collation do MySQL escondia.
CREATE UNIQUE INDEX idx_perfil_email ON perfil (email);
