CREATE TABLE carrinho (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Um carrinho por cliente. O identificador é o "sub" do token, não um id
    -- de tabela de usuário: o dono do usuário é o Keycloak.
    cliente_sub VARCHAR(64) NOT NULL UNIQUE
);

CREATE TABLE item_carrinho (
    id             BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carrinho_id    BIGINT        NOT NULL REFERENCES carrinho (id) ON DELETE CASCADE,
    produto_id     BIGINT        NOT NULL,
    tamanho_id     BIGINT        NOT NULL,
    sigla          VARCHAR(2)    NOT NULL,
    quantidade     INTEGER       NOT NULL CHECK (quantidade > 0),
    valor_unitario NUMERIC(19,4) NOT NULL
);

CREATE INDEX idx_item_carrinho_carrinho ON item_carrinho (carrinho_id);

CREATE TABLE pedido (
    id                   BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_sub          VARCHAR(64)   NOT NULL,
    cliente_email        VARCHAR(200)  NOT NULL,
    valor_total          NUMERIC(19,4) NOT NULL,
    status               VARCHAR(20)   NOT NULL,
    -- NULL = o serviço ainda não respondeu. É o que permite tratar por estado
    -- final em vez de por ordem de chegada.
    estoque_reservado    BOOLEAN,
    pagamento_confirmado BOOLEAN,
    payment_intent_id    VARCHAR(100),
    motivo_cancelamento  VARCHAR(500),
    criado_em            TIMESTAMPTZ   NOT NULL,
    atualizado_em        TIMESTAMPTZ
);

CREATE INDEX idx_pedido_cliente ON pedido (cliente_sub, criado_em DESC);

CREATE TABLE item_pedido (
    id             BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id      BIGINT        NOT NULL REFERENCES pedido (id) ON DELETE CASCADE,
    produto_id     BIGINT        NOT NULL,
    tamanho_id     BIGINT        NOT NULL,
    sigla          VARCHAR(2)    NOT NULL,
    quantidade     INTEGER       NOT NULL CHECK (quantidade > 0),
    valor_unitario NUMERIC(19,4) NOT NULL,
    enviado        BOOLEAN       NOT NULL DEFAULT FALSE,
    recebido       BOOLEAN       NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_item_pedido_pedido ON item_pedido (pedido_id);
CREATE INDEX idx_item_pedido_enviado ON item_pedido (enviado);
