CREATE TABLE pagamento (
    id                BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Um pagamento por pedido. A constraint é o que impede duas cobranças
    -- para o mesmo pedido se o evento chegar duplicado.
    order_id          BIGINT        NOT NULL UNIQUE,
    cliente_sub       VARCHAR(64)   NOT NULL,
    payment_intent_id VARCHAR(100)  UNIQUE,
    charge_id         VARCHAR(100),
    refund_id         VARCHAR(100),
    valor             NUMERIC(19,4) NOT NULL,
    status            VARCHAR(20)   NOT NULL,
    motivo_falha      VARCHAR(500),
    criado_em         TIMESTAMPTZ   NOT NULL,
    atualizado_em     TIMESTAMPTZ
);

CREATE INDEX idx_pagamento_status ON pagamento (status);

CREATE TABLE webhook_recebido (
    -- A chave é o id do evento NA STRIPE: é o que deduplica a reentrega.
    stripe_event_id VARCHAR(100) PRIMARY KEY,
    tipo            VARCHAR(100) NOT NULL,
    payload         JSONB        NOT NULL,
    processado      BOOLEAN      NOT NULL DEFAULT FALSE,
    recebido_em     TIMESTAMPTZ  NOT NULL,
    erro            VARCHAR(1000)
);

CREATE INDEX idx_webhook_pendente ON webhook_recebido (recebido_em) WHERE NOT processado;
