-- Tradução do schema do MySQL: TINYINT(1) -> BOOLEAN, INT AUTO_INCREMENT ->
-- GENERATED BY DEFAULT AS IDENTITY, DATETIME -> TIMESTAMPTZ, DECIMAL -> NUMERIC.

CREATE TABLE produto (
    id            BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome          VARCHAR(120)  NOT NULL,
    preco         NUMERIC(19,4) NOT NULL,
    descricao     VARCHAR(2000) NOT NULL,
    categoria     VARCHAR(40)   NOT NULL,
    criado_em     TIMESTAMPTZ   NOT NULL,
    atualizado_em TIMESTAMPTZ
);

CREATE TABLE tamanho (
    id          BIGINT     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id  BIGINT     NOT NULL REFERENCES produto (id) ON DELETE CASCADE,
    sigla       VARCHAR(2) NOT NULL,
    quantidade  INTEGER    NOT NULL,
    -- O estoque nunca fica negativo nem por bug de aplicação: o banco recusa.
    CONSTRAINT tamanho_quantidade_nao_negativa CHECK (quantidade >= 0),
    CONSTRAINT tamanho_sigla_unica_por_produto UNIQUE (produto_id, sigla)
);

CREATE INDEX idx_tamanho_produto ON tamanho (produto_id);

CREATE TABLE foto (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id BIGINT       NOT NULL REFERENCES produto (id) ON DELETE CASCADE,
    url        VARCHAR(500) NOT NULL
);

CREATE INDEX idx_foto_produto ON foto (produto_id);

CREATE TABLE reserva_estoque (
    id         BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   BIGINT  NOT NULL,
    tamanho_id BIGINT  NOT NULL REFERENCES tamanho (id),
    quantidade INTEGER NOT NULL,
    liberada   BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_reserva_pedido_ativa ON reserva_estoque (order_id) WHERE NOT liberada;
